switching helper-status-checker chart to verify the operator status instead of the deployment. Updated chart to 2.0

diff --git a/charts/helper-status-checker/templates/check_if_operator_is_ready.yaml b/charts/helper-status-checker/templates/check_if_operator_is_ready.yaml
--- a/charts/helper-status-checker/templates/check_if_operator_is_ready.yaml
+++ b/charts/helper-status-checker/templates/check_if_operator_is_ready.yaml
@@ -22,28 +22,81 @@ spec:
             - -c
             - |
              #!/usr/bin/env bash
-             sleep_timer={{ .wait_time | default 20 }}
+             sleep_timer={{ .sleeptimer | default 20 }}
+             max_timer={{ .maxretries | default 20 }}
+             counter=0
              status=0
 
-             echo "Waiting for operator to be available..."
+             echo "Starting operator status checker"
+             operator={{ .operatorName }}
+             printf "\nWaiting for operator %s to appear\n" "$i";
 
-             # turned out it takes even more time until operator is ready, so lets check the deployment
-             deployments=({{ .deployments }})
-             for i in "${deployments[@]}";
-             do
-                printf "\nWaiting for deployment %s\n" "$i";
-                oc get deployment/"$i" -n {{ .namespace.name | quote }}
-                depl_status=$?
-                if [ $depl_status -eq 1 ]; then
-                    echo "Deployment not yet found... Give Operator $sleep_timer seconds to create the Deployment"
-                    sleep $sleep_timer
-                fi
-                oc rollout status deployment "$i" -n {{ .namespace.name | quote }}
-                status=$?
+             # Wait until operator appears
+             get_exact_name=`oc get clusterserviceversion -n {{ .namespace.name }} | grep $operator | awk -F" " '{print $1}'`
+             until [ "$get_exact_name" != "" ]; do
+               # do not wait forever
+               let "counter=counter+1"
+               echo "Attempt $counter of $max_timer"
+
+               if [[ $counter -eq $max_timer ]]
+               then
+                 echo "Giving up. Operator does not appear as clusterserviceversion"
+                 exit 3
+               fi
+
+               echo "Operator not yet found... Give Operator $sleep_timer seconds to create the Deployment"
+               sleep $sleep_timer
+               get_exact_name=`oc get clusterserviceversion -n {{ .namespace.name }} | grep $operator | awk -F" " '{print $1}'`
              done
 
-             echo $status
+             # Get exact name of the operator
+             counter=0
+             get_status=`oc get clusterserviceversion -n {{ .namespace.name }} $get_exact_name -o jsonpath={.status.phase}`
+             until [ "$get_status" != "" ]; do
+               # do not wait forever
+               let "counter=counter+1"
+               echo "Attempt $counter of $max_timer"
 
+               if [[ $counter -eq $max_timer ]]
+               then
+                 echo "Giving up. Operator installation failed"
+                 exit 3
+               fi
+
+               echo "Operator not yet ready ... Waiting $sleep_timer seconds"
+               sleep $sleep_timer
+               get_status=`oc get clusterserviceversion -n {{ .namespace.name }} $get_exact_name -o jsonpath={.status.phase}`
+             done
+
+             echo "Checking status of $get_exact_name. Current status: $get_status"
+
+             # Wait until operator is ready
+             counter=0
+             until [ "$get_status" == "Succeeded" ]; do
+             let "counter=counter+1"
+               echo "Attempt $counter of $max_timer"
+
+               if [[ $counter -eq $max_timer ]]
+               then
+                 echo "Giving up. Operator installation failed"
+                 exit 3
+               fi
+
+               echo "Operator deployment is ongoing. Current status: $get_status"
+               sleep $sleep_timer
+               if [ "$get_status" == "Succeeded" ];
+               then
+                 status=$?
+               fi
+               get_status=`oc get clusterserviceversion -n {{ .namespace.name }} $get_exact_name -o jsonpath={.status.phase}`
+             done
+
+             oc get clusterserviceversion -n {{ .namespace.name }} $get_exact_name
+
+             echo "Falling to sleep"
+             sleep 10
+
+             printf "\nStatus: $status\n"
              if [ $status -eq 0 ]; then
                   echo "Operator seems to be ready"
              else
